import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { boundedBrowserTimeout } from './browser_acceptance_runtime.mjs';

const baseUrl=process.argv[2];if(!baseUrl)throw new Error('Usage: node scripts/browser_settings_provider_smoke.mjs <base-url>');
const exe=[process.env.STORY_AUDIO_BROWSER_EXE,'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe','C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'].filter(Boolean).find(existsSync);if(!exe)throw new Error('No Chromium browser');
const profile=await mkdtemp(join(tmpdir(),'story-audio-settings-'));const child=spawn(exe,['--headless=new','--disable-gpu','--no-first-run','--remote-debugging-port=0',`--user-data-dir=${profile}`,`${baseUrl}/#/settings`],{stdio:'ignore'});const delay=ms=>new Promise(r=>setTimeout(r,ms));async function poll(fn,t=20000){const end=Date.now()+boundedBrowserTimeout(t);let last;while(Date.now()<end){try{const v=await fn();if(v)return v}catch(e){last=e}await delay(60)}throw last||new Error('timeout')}
let socket;try{const port=await poll(async()=>Number((await readFile(join(profile,'DevToolsActivePort'),'utf8')).split(/\r?\n/)[0])||null);const page=await poll(async()=>{const pages=await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();return pages.find(p=>p.type==='page'&&p.url.startsWith(baseUrl))});socket=new WebSocket(page.webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j});let id=0;const pending=new Map(),errors=[];socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')errors.push(m.params?.exceptionDetails?.exception?.description||m.params?.exceptionDetails?.text||'runtime');const w=pending.get(m.id);if(!w)return;pending.delete(m.id);m.error?w.reject(new Error(m.error.message)):w.resolve(m.result)};const send=(method,params={})=>new Promise((resolve,reject)=>{const rid=++id;pending.set(rid,{resolve,reject});socket.send(JSON.stringify({id:rid,method,params}))});const ev=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value};const wait=(x,t=20000)=>poll(async()=>await ev(x),t);await send('Runtime.enable');await wait(`document.readyState==='complete'&&document.querySelector('#settingsSaveGeminiKeys')&&window.storyAudioAppState?.config`);
const before=await ev(`({status:document.querySelector('#settingsGeminiKeyStatus').textContent,tts:document.querySelector('#settingsTtsStatus').textContent})`);
await ev(`(()=>{const el=document.querySelector('#settingsGeminiKeys');el.value='key-a\\nkey-b\\nkey-a';el.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#settingsSaveGeminiKeys').click();return true})()`);await wait(`document.querySelector('#settingsGeminiKeyResult').textContent.includes('Đã thêm 2 key')`);const first=await ev(`({result:document.querySelector('#settingsGeminiKeyResult').textContent,status:document.querySelector('#settingsGeminiKeyStatus').textContent,cleared:document.querySelector('#settingsGeminiKeys').value==='',secretVisible:document.body.innerText.includes('key-a')||document.body.innerText.includes('key-b')})`);
await ev(`(()=>{const el=document.querySelector('#settingsGeminiKeys');el.value='key-b';document.querySelector('#settingsSaveGeminiKeys').click();return true})()`);await wait(`document.querySelector('#settingsGeminiKeyResult').textContent.includes('bỏ qua 1 key trùng')`);const duplicate=await ev(`document.querySelector('#settingsGeminiKeyResult').textContent`);
await ev(`document.querySelector('#settingsProbeTts').click()`);await wait(`document.querySelector('#settingsTtsResult').textContent.includes('TTS sẵn sàng')`);const tts=await ev(`({result:document.querySelector('#settingsTtsResult').textContent,status:document.querySelector('#settingsTtsStatus').textContent,health:document.querySelector('#health').textContent})`);const providerRecovery=await ev(`(async()=>{state.productionPrepare.readiness={start_render_allowed:false,start_render_blocker_codes:['PROVIDER_NOT_READY'],prepare_allowed:true};state.productionPreflight={execution_readiness:{prepared_job:null}};const vm={task_type:'START_RENDER',task_summary:'Ready to render',render:{job_status:''},primary_action:{key:'FOCUS_BLOCKER'}};const projected=unifiedProductionJourneyView(vm);await runProductionPrimaryAction(vm);await new Promise(r=>setTimeout(r,0));return{key:projected.primary_action?.key,label:projected.primary_action?.label,hash:location.hash,focused:document.activeElement?.id||''}})()`);if(errors.length)throw new Error(errors.join(' | '));process.stdout.write(JSON.stringify({ok:true,before,first,duplicate,tts,providerRecovery}));}finally{try{socket?.close()}catch{}child.kill();await delay(250);await rm(profile,{recursive:true,force:true}).catch(()=>{})}
