#!/usr/bin/env python3
"""CLI schema for Senior AI Build OS v1.16.

Kept separate from lifecycle mutation so command-surface changes do not expand the
core task/goal kernel.
"""
from __future__ import annotations
import argparse
from pathlib import Path

DEFAULT_ROOT = Path(__file__).resolve().parents[1]

def add_metrics(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--skip-ledger", action="store_true"); parser.add_argument("--cycle-minutes", type=float)
    parser.add_argument("--first-pass-accepted", choices=["yes", "no", "unknown"], default="unknown")
    for name in ["coordination-input-tokens", "implementation-input-tokens", "cached-input-tokens", "output-tokens", "worker-turns", "retries", "provider-runs", "human-review-minutes", "human-wait-minutes"]:
        parser.add_argument(f"--{name}", type=int)
    parser.add_argument("--estimated-ai-cost", type=float); parser.add_argument("--provider-cost", type=float)
    parser.add_argument("--currency", default="USD"); parser.add_argument("--rollback-required", choices=["yes", "no"], default="no"); parser.add_argument("--notes", default="")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Senior AI Build OS v1.16")
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    sub = parser.add_subparsers(dest="command", required=True)

    init = sub.add_parser("init")
    init.add_argument("--project-id", required=True)
    init.add_argument("--owner", required=True)
    init.add_argument("--problem", required=True)
    init.add_argument("--target-user", required=True)
    init.add_argument("--primary-action", required=True)
    init.add_argument("--observable-result", required=True)
    init.add_argument("--mvp-goal", required=True)
    init.add_argument("--acceptance-threshold", default="observable result passes representative fixtures")
    init.add_argument("--demo-method", default="local runtime demo")
    init.add_argument("--milestone-id", default="M-001")
    init.add_argument("--no-ci", action="store_true", help="Do not install the managed GitHub Actions workflow")

    start_p = sub.add_parser("start", aliases=["begin"])
    start_p.add_argument("--task-id", required=True)
    start_p.add_argument("--outcome", required=True)
    start_p.add_argument("--risk", default="auto", choices=["auto", "R0", "R1", "R2", "R3"])
    start_p.add_argument("--success-criterion", required=True)
    start_p.add_argument("--accept", action="append", default=[], help="Concrete acceptance criterion; repeat for multiple checks")
    start_p.add_argument("--delivery-delta", required=True, choices=["USER_VISIBLE_BEHAVIOR", "EXECUTABLE_CAPABILITY", "RISK_RETIREMENT", "DOCUMENTATION_ONLY", "NO_DELTA"])
    start_p.add_argument("--milestone-id", default="M-001")
    start_p.add_argument("--project-id")
    start_p.add_argument("--goal-id", default=None, help="Link this task to the active Goal")
    start_p.add_argument("--goal-node", default=None, help="Goal DAG node for machine-to-machine orchestration")
    start_p.add_argument("--demonstrable-result", default="runtime/output evidence listed in task evidence index")
    start_p.add_argument("--unlocks", default="next milestone capability")
    start_p.add_argument("--read-scope", default="task-relevant repository files")
    start_p.add_argument("--modify", required=True)
    start_p.add_argument("--create", default="NONE")
    start_p.add_argument("--replaces", action="append", default=[], help="Obsolete path that must be removed by acceptance; repeat as needed")
    start_p.add_argument("--commands", default="focused checks and task-authorized commands")
    start_p.add_argument("--local-services", default="NONE")
    start_p.add_argument("--external-calls", default="NONE")
    start_p.add_argument("--data-operation", choices=["READ_ONLY", "CREATE_NEW_VERSION", "MUTATE_IN_PLACE", "DELETE"], default="READ_ONLY")
    start_p.add_argument("--artifact-operation", choices=["READ_ONLY", "CREATE_NEW_VERSION", "MUTATE_IN_PLACE", "OVERWRITE", "DELETE"], default="CREATE_NEW_VERSION")
    start_p.add_argument("--inputs", default="task-relevant source and fixtures")
    start_p.add_argument("--outputs", default="accepted outcome and evidence")
    start_p.add_argument("--files-created", default="NONE")
    start_p.add_argument("--files-overwritten", default="NONE")
    start_p.add_argument("--data-mutated", default="NONE")
    start_p.add_argument("--provider-calls", default="NONE")
    start_p.add_argument("--expected-provider-cost", type=float, default=0.0)
    start_p.add_argument("--disk-requirement", default="MINIMAL")
    start_p.add_argument("--ram-requirement", default="MINIMAL")
    start_p.add_argument("--process-port", default="NONE")
    start_p.add_argument("--artifact-lineage", default="source inputs and evidence manifest")
    start_p.add_argument("--rollback", default="revert task-scoped diff and remove new artifacts")
    start_p.add_argument("--expected-cost-range", default="small; investigate repeated attempts without evidence")
    start_p.add_argument("--primary-cost-drivers", default="implementation, verification and output inspection")
    start_p.add_argument("--evidence-sequence", default="focused → affected regression/runtime → diff review")
    start_p.add_argument("--escalation-conditions", default="risk exceeds profile or same approach fails twice")
    start_p.add_argument("--negative-required", action="store_true", help="Require an explicit negative/failure-path check even on Fast Lane")
    start_p.add_argument("--state-hazard", default="auto", choices=["auto","S0","S1","S2","S3","S4"], help="State/temporal hazard gate; auto is zero-ceremony for stateless work")
    start_p.add_argument("--state-signal", action="append", default=[], help="Optional high-signal state mechanism, e.g. draft, persistence, polling, hydration, cache")
    start_p.add_argument("--state-authority", default="", help="S2+ authoritative persisted/source state, kept intentionally short")
    start_p.add_argument("--state-transition", action="append", default=[], help="S2+ representative transition, e.g. SAVED -> DIRTY -> SAVE -> SAVED")
    start_p.add_argument("--state-invariant", action="append", default=[], help="S2+ overwrite/reconciliation invariant")
    start_p.add_argument("--state-dependency", action="append", default=[], help="Files/globs that invalidate reusable state proof; defaults to task modify/create scope")
    start_p.add_argument("--owner-authorization", choices=["NOT_REQUIRED", "APPROVED"], default="NOT_REQUIRED")
    start_p.add_argument("--authorization-reference", default="")
    start_p.add_argument("--breaker-override", action="store_true", help="Explicitly allow a non-shipping task while the shipping breaker is active")
    start_p.add_argument("--breaker-override-reason", default="", help="Audit reason required with --breaker-override")
    start_p.add_argument("--stop-loss-ack", default="", help="Required only after two consecutive prior revisions with first_pass_accepted=no")
    claim_mode = start_p.add_mutually_exclusive_group()
    claim_mode.add_argument("--claim", dest="claim", action="store_true", help="Auto-claim writer lease (default)")
    claim_mode.add_argument("--ready", "--no-claim", dest="claim", action="store_false", help="Create READY task without claiming it")
    start_p.set_defaults(claim=True)
    start_p.add_argument("--writer-role", default="WORKER")
    start_p.add_argument("--platform", default="ChatGPT")
    start_p.add_argument("--session-label", default="AI-WORKER")
    start_p.add_argument("--allow-no-git", action="store_true")

    claim = sub.add_parser("claim")
    claim.add_argument("--writer-role", default="WORKER")
    claim.add_argument("--platform", default="ChatGPT")
    claim.add_argument("--session-label", default="AI-WORKER")
    sub.add_parser("pause")
    resume = sub.add_parser("resume")
    resume.add_argument("--writer-role", default="WORKER")
    resume.add_argument("--platform", default="ChatGPT")
    resume.add_argument("--session-label", default="AI-WORKER")
    sub.add_parser("abort")

    amend = sub.add_parser("amend")
    amend.add_argument("--add-modify")
    amend.add_argument("--add-create")
    amend.add_argument("--risk", choices=["R0", "R1", "R2", "R3"])
    amend.add_argument("--data-operation", choices=["READ_ONLY", "CREATE_NEW_VERSION", "MUTATE_IN_PLACE", "DELETE"])
    amend.add_argument("--artifact-operation", choices=["READ_ONLY", "CREATE_NEW_VERSION", "MUTATE_IN_PLACE", "OVERWRITE", "DELETE"])
    amend.add_argument("--files-overwritten")
    amend.add_argument("--data-mutated")
    amend.add_argument("--external-calls")
    amend.add_argument("--provider-calls")
    amend.add_argument("--owner-authorization", choices=["APPROVED"])
    amend.add_argument("--authorization-reference", default="")
    amend.add_argument("--reason", required=True)

    runnable = sub.add_parser("runnable")
    runnable.add_argument("--evidence", required=True)
    runnable.add_argument("--at")

    done = sub.add_parser("done")
    done.add_argument("--outcome", required=True)
    done.add_argument("--focused-command", action="append", default=[])
    done.add_argument("--negative-command", action="append", default=[])
    done.add_argument("--integration-command", action="append", default=[])
    done.add_argument("--state-transition-command", action="append", default=[], help="S2+ transition proof; exact proof is reused while contract/dependencies are unchanged")
    done.add_argument("--state-temporal-command", action="append", default=[], help="S3+ temporal/background-writer proof; reusable until affected source changes")
    done.add_argument("--rollback-command", action="append", default=[], help="R3 rollback rehearsal/proof; must leave final application state intact")
    done.add_argument("--full-suite-command", action="append", default=[])
    done.add_argument("--artifact", action="append", default=[])
    done.add_argument("--review-report")
    done.add_argument("--review-attestation", help="Optional outer-runtime JSON attestation outside repo; upgrades review trust from DECLARED to ATTESTED")
    done.add_argument("--command-timeout", type=int, default=300)
    done.add_argument("--allow-shell-command", action="store_true")
    done.add_argument("--output-inspected-by")
    done.add_argument("--expected-output", action="append", default=[], help="Optional exact marker that must appear in stored verification stdout/stderr")
    done.add_argument("--cleanup-note", default="no residual process; rollback remains available")
    done.add_argument("--known-limits", default="NONE")
    done.add_argument("--dependency-justification", default="", help="Optional free-form note; structured dependency fields are required when runtime dependency count increases")
    done.add_argument("--dependency-capability", default="", help="Concrete production capability bought by a new runtime dependency")
    done.add_argument("--dependency-alternatives-considered", default="", help="Built-in/existing alternatives considered before adding a runtime dependency")
    done.add_argument("--dependency-removal-cost", default="", help="Expected coupling/removal cost or exit path for a new runtime dependency")
    add_metrics(done)

    close = sub.add_parser("close")
    close.add_argument("--outcome", required=True)
    close.add_argument("--evidence-bundle", required=True)
    close.add_argument("--delivery-delta", choices=["USER_VISIBLE_BEHAVIOR", "EXECUTABLE_CAPABILITY", "RISK_RETIREMENT", "DOCUMENTATION_ONLY", "NO_DELTA"])
    close.add_argument("--completed-at")
    add_metrics(close)
    close.set_defaults(focused_test_runs=None, integration_test_runs=None, full_suite_runs=None)

    check_p = sub.add_parser("check")
    check_p.add_argument("--strict", action="store_true")
    sub.add_parser("doctor")
    status = sub.add_parser("status")
    status.add_argument("--json", action="store_true")
    sub.add_parser("next")
    history = sub.add_parser("history")
    history.add_argument("--limit", type=int, default=20)
    report_p = sub.add_parser("report")
    report_p.add_argument("--last", type=int, default=30)
    rec = sub.add_parser("reconcile")
    rec.add_argument("--task-id", required=True)
    rec.add_argument("--task-revision", type=int, required=True)
    rec.add_argument("--later-rework", choices=["yes", "no", "unknown"])
    rec.add_argument("--escaped-defect", choices=["yes", "no", "unknown"])
    rec.add_argument("--rollback-required", choices=["yes", "no"])
    rec.add_argument("--notes")
    rec.add_argument("--human-review-minutes", type=int)
    rec.add_argument("--human-wait-minutes", type=int)

    route = sub.add_parser("route", help="Recommend FAST/STANDARD/GOAL lane before materializing orchestration")
    route.add_argument("--outcome", required=True)
    route.add_argument("--accept", action="append", default=[])
    route.add_argument("--modify", required=True)
    route.add_argument("--risk", default="auto", choices=["auto","R0","R1","R2","R3"])
    route.add_argument("--dependency-count", type=int, default=0)
    route.add_argument("--acceptance-surfaces", type=int, default=1)
    route.add_argument("--parallel-opportunity", action="store_true")
    route.add_argument("--json", action="store_true")

    sub.add_parser("assurance", help="Show achieved enforcement assurance A0-A4 and missing trust-boundary prerequisites")

    debug = sub.add_parser("debug", help="Record bounded state failure signatures without global tracing")
    dsub = debug.add_subparsers(dest="debug_command", required=True)
    df = dsub.add_parser("state-failure")
    df.add_argument("--state", required=True); df.add_argument("--event", required=True)
    df.add_argument("--expected", required=True); df.add_argument("--observed", required=True)
    df.add_argument("--hazard-class", default="UNKNOWN"); df.add_argument("--suspect", action="append", default=[])
    di = dsub.add_parser("evidence-infra-failure", help="Record verifier/harness failure for the two-strike method-change stop-loss")
    di.add_argument("--method", required=True); di.add_argument("--note", default="")

    field = sub.add_parser("field", help="Record/report normalized real-world OS friction and failure signals")
    fsub = field.add_subparsers(dest="field_command", required=True)
    fr = fsub.add_parser("record")
    fr.add_argument("--event-type", required=True)
    fr.add_argument("--phase", default="UNKNOWN")
    fr.add_argument("--severity", choices=["LOW","MEDIUM","HIGH","CRITICAL"], default="LOW")
    fr.add_argument("--trigger", default="")
    fr.add_argument("--extra-wall-seconds", type=float, default=0.0)
    fr.add_argument("--extra-input-tokens", type=int, default=0)
    fr.add_argument("--extra-output-tokens", type=int, default=0)
    fr.add_argument("--extra-provider-cost", type=float, default=0.0)
    fr.add_argument("--evidence-code", default="")
    frep=fsub.add_parser("report"); frep.add_argument("--last",type=int,default=500); frep.add_argument("--global",dest="global_scope",action="store_true",help="Read optional privacy-redacted cross-project event store")

    health = sub.add_parser("health", help="Codebase-health ratchet, bloat guard and hotspot reporting")
    hsub = health.add_subparsers(dest="health_command", required=True)
    hsub.add_parser("baseline")
    hc = hsub.add_parser("check"); hc.add_argument("--ci", action="store_true")
    hsub.add_parser("report")
    haw = hsub.add_parser("architecture-decision", help="Record an explicit reason when this executable project intentionally has no enforceable module boundaries yet")
    haw.add_argument("--no-boundaries-reason", required=True)

    telemetry = sub.add_parser("telemetry", help="Provider-neutral outer-runtime usage ingestion")
    tsub = telemetry.add_subparsers(dest="telemetry_command", required=True)
    ti = tsub.add_parser("ingest"); ti.add_argument("--file", required=True)
    tsub.add_parser("report")

    goal = sub.add_parser("goal", help="Goal-level planning/orchestration above the task execution kernel")
    gsub = goal.add_subparsers(dest="goal_command", required=True)
    gdec = gsub.add_parser("decision", help="Record an assumption/auto/owner/risk/policy decision for later owner digest")
    gdec.add_argument("--type", choices=["ASSUMPTION","AUTO_DECISION","OWNER_DECISION","RISK_ESCALATION","POLICY_EXCEPTION"], required=True)
    gdec.add_argument("--text", required=True)
    gdec.add_argument("--confidence", type=float)
    gdec.add_argument("--reversibility", choices=["HIGH","MEDIUM","LOW","UNKNOWN"], default="UNKNOWN")
    gdec.add_argument("--owner-impact", choices=["LOW","MEDIUM","HIGH","CRITICAL"], default="LOW")
    gdec.add_argument("--reason", default="")
    gdigest=gsub.add_parser("digest", help="Summarize decisions the orchestrator made without interrupting the owner")
    gdigest.add_argument("--goal-id")

    gb = gsub.add_parser("begin")
    gb.add_argument("--goal-id")
    gb.add_argument("--goal", "--outcome", dest="goal_outcome", required=True)
    gb.add_argument("--accept", action="append", default=[], required=True)
    gb.add_argument("--non-goal", action="append", default=[])
    gb.add_argument("--type", dest="goal_type", choices=["product", "maintenance", "risk"], default="product")
    gb.add_argument("--risk-ceiling", choices=["R0", "R1", "R2", "R3"], default="R2")
    gb.add_argument("--max-tasks", type=int, default=8)
    gb.add_argument("--max-parallel", type=int, default=1)
    gb.add_argument("--max-non-shipping", type=int, default=2)
    gb.add_argument("--max-revisions", type=int, default=2)
    gb.add_argument("--scope-growth-limit", type=int, default=30)
    gb.add_argument("--max-auto-scouts", type=int, default=2, help="Cost guard: maximum high-confidence auto-inserted read-only Scouts per Goal")
    gb.add_argument("--scout-summary-token-budget", type=int, default=350, help="Maximum approximate tokens returned by each Scout to the orchestrator")
    gb.add_argument("--scout-input-token-budget", type=int, default=24000, help="Observed Scout input-token ceiling when runtime telemetry is available")
    gb.add_argument("--scout-wall-minutes-budget", type=float, default=5.0, help="Observed Scout wall-time ceiling")
    gb.add_argument("--scout-provider-cost-budget", type=float, default=0.0, help="Optional provider-cost ceiling; 0 disables because provider pricing varies")

    ga = gsub.add_parser("add-task")
    ga.add_argument("--node", required=True)
    ga.add_argument("--outcome", required=True)
    ga.add_argument("--depends-on", action="append", default=[])
    ga.add_argument("--agent-role", choices=["SCOUT", "WORKER", "REVIEWER"], default="WORKER")
    ga.add_argument("--risk", choices=["auto", "R0", "R1", "R2", "R3"], default="auto")
    ga.add_argument("--delivery-delta", choices=["USER_VISIBLE_BEHAVIOR", "EXECUTABLE_CAPABILITY", "RISK_RETIREMENT", "DOCUMENTATION_ONLY", "NO_DELTA"], required=True)
    ga.add_argument("--modify", required=True)
    ga.add_argument("--create", default="NONE")
    ga.add_argument("--replaces", action="append", default=[])
    ga.add_argument("--success-criterion", default="SC-001")
    ga.add_argument("--accept", action="append", default=[])
    ga.add_argument("--negative-required", action="store_true")
    ga.add_argument("--data-operation", choices=["READ_ONLY", "CREATE_NEW_VERSION", "MUTATE_IN_PLACE", "DELETE"], default="READ_ONLY")
    ga.add_argument("--artifact-operation", choices=["READ_ONLY", "CREATE_NEW_VERSION", "MUTATE_IN_PLACE", "OVERWRITE", "DELETE"], default="CREATE_NEW_VERSION")
    ga.add_argument("--acceptance-command", action="append", default=[], help="Predeclared judge command; required before starting Goal-linked R2/R3 workers")
    ga.add_argument("--expected-output", action="append", default=[], help="Optional predeclared semantic marker for the acceptance contract")
    ga.add_argument("--probe-file", action="append", default=[], help="Optional read-only acceptance/test probe file whose hash is frozen before Worker start")
    ga.add_argument("--review-policy", choices=["auto", "required", "none"], default="auto", help="R2 reviewer policy; R3 remains mandatory")
    ga.add_argument("--delegation-policy", choices=["auto", "main", "scout"], default="auto", help="Cost-aware pre-scout policy. auto only inserts Scout for high-confidence discovery-heavy work")
    ga.add_argument("--state-hazard", default="auto", choices=["auto","S0","S1","S2","S3","S4"])
    ga.add_argument("--state-signal", action="append", default=[])
    ga.add_argument("--state-authority", default="")
    ga.add_argument("--state-transition", action="append", default=[])
    ga.add_argument("--state-invariant", action="append", default=[])
    ga.add_argument("--state-dependency", action="append", default=[])

    gac = gsub.add_parser("bind-acceptance", help="Bind a declared Goal criterion to its judge before the first Worker starts")
    gac.add_argument("--criterion", type=int, required=True, help="1-based Goal acceptance criterion index")
    gac.add_argument("--command", dest="judge_command", default="")
    gac.add_argument("--expected-output", default="")
    gac.add_argument("--probe-file", default="")
    gac.add_argument("--inspection-requirement", default="")

    gs = gsub.add_parser("start")
    gs.add_argument("--node", required=True)
    gs.add_argument("--platform", default="ChatGPT")
    gs.add_argument("--session-label", default="AI-WORKER")
    gs.add_argument("--owner-authorization", choices=["NOT_REQUIRED", "APPROVED"], default="NOT_REQUIRED")
    gs.add_argument("--authorization-reference", default="")
    gs.add_argument("--stop-loss-ack", default="")
    gs.add_argument("--allow-no-git", action="store_true")

    gstatus = gsub.add_parser("status"); gstatus.add_argument("--json", action="store_true")
    gnext = gsub.add_parser("next"); gnext.add_argument("--json", action="store_true")
    gd = gsub.add_parser("discover")
    gd.add_argument("--summary", required=True)
    gd.add_argument("--affected-file", action="append", default=[])
    gd.add_argument("--risk-signal", action="append", default=[])
    gsd = gsub.add_parser("scout-done", aliases=["node-done"])
    gsd.add_argument("--node", required=True); gsd.add_argument("--summary", required=True)
    gsd.add_argument("--affected-file", action="append", default=[]); gsd.add_argument("--risk-signal", action="append", default=[])
    gsd.add_argument("--input-tokens", type=int); gsd.add_argument("--output-tokens", type=int)
    gsd.add_argument("--provider-cost", type=float); gsd.add_argument("--wall-minutes", type=float)
    gsd.add_argument("--invariant", action="append", default=[]); gsd.add_argument("--entry-point", default="")
    gsd.add_argument("--confidence", choices=["LOW","MEDIUM","HIGH"], default="MEDIUM")
    gsd.add_argument("--recommended-scope", action="append", default=[])
    gdef = gsub.add_parser("defer"); gdef.add_argument("--node", required=True); gdef.add_argument("--reason", required=True)
    gblock = gsub.add_parser("block"); gblock.add_argument("--reason", required=True); gblock.add_argument("--owner-decision", action="store_true")
    gres = gsub.add_parser("resume"); gres.add_argument("--decision", default="")
    gabort = gsub.add_parser("abort"); gabort.add_argument("--reason", required=True)
    gdone = gsub.add_parser("done")
    gdone.add_argument("--inspection-confirm", action="append", type=int, default=[], help="Confirm frozen inspection criterion index; declared inspection, not cryptographic attestation")
    gdone.add_argument("--output-inspected-by", required=True)
    gdone.add_argument("--known-limits", default="NONE")
    gdone.add_argument("--command-timeout", type=int, default=300)
    gdone.add_argument("--allow-shell-command", action="store_true")
    return parser
