const $=s=>document.querySelector(s);let state={config:null,books:[],book:null,page:0,pageSize:100,total:0,previewOk:false,dialog:null};
async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let data;try{data=await r.json()}catch{data={detail:await r.text()}}if(!r.ok)throw new Error(data.detail||data.error||'Yêu cầu thất bại');return data}
function toast(msg,error=false){const el=$('#toast');el.textContent=msg;el.className='toast'+(error?' error':'');setTimeout(()=>el.classList.add('hidden'),4500)}
function fmtStatus(s){return({scheduled:'Chờ hoàn tác',queued:'Đang chờ',running:'Đang chạy',repairing:'Gemini',synthesizing:'Đang đọc',assembling:'Đang ghép',paused:'Tạm dừng',completed:'Hoàn tất',completed_with_errors:'Xong có lỗi',failed:'Thất bại',cancelled:'Đã hủy',interrupted:'Bị gián đoạn'})[s]||s}
async function init(){try{state.config=await api('/api/config');$('#health').textContent=`Gemini: ${state.config.gemini_configured?'sẵn sàng':'chưa có key'} · VieNeu: ${state.config.tts_status}`;$('#epubPath').innerHTML=state.config.available_epubs.map(p=>`<option value="${p}">${p.split(/[\\/]/).pop()}</option>`).join('')||'<option>Không tìm thấy EPUB</option>';await loadBooks();await loadJobs()}catch(e){toast(e.message,true)}setInterval(loadJobs,2500)}
async function loadBooks(){state.books=await api('/api/books');$('#books').innerHTML=state.books.map(b=>`<div class="book-card ${state.book?.id===b.id?'active':''}" data-id="${b.id}"><strong>${esc(b.title)}</strong><span>${esc(b.author||'Không rõ tác giả')} · ${b.chapter_count} chương · ${b.audio_chapters||0} có audio</span></div>`).join('')||'<p class="muted">Chưa nhập sách.</p>';document.querySelectorAll('.book-card').forEach(el=>el.onclick=()=>selectBook(+el.dataset.id))}
async function selectBook(id){state.book=state.books.find(b=>b.id===id);state.page=0;state.previewOk=false;$('#workspace').classList.remove('hidden');$('#bookTitle').textContent=state.book.title;$('#chapterCount').textContent=`${state.book.chapter_count} chương`;$('#fromChapter').value=1;$('#toChapter').value=Math.min(10,state.book.chapter_count);await loadBooks();await loadChapters()}
async function loadChapters(){if(!state.book)return;const q=encodeURIComponent($('#chapterQuery').value.trim());const data=await api(`/api/books/${state.book.id}/chapters?offset=${state.page*state.pageSize}&limit=${state.pageSize}&query=${q}`);state.total=data.total;$('#chapterList').innerHTML=data.items.map(c=>`<div class="chapter-row" data-id="${c.id}"><span class="chapter-number">${c.chapter_number}</span><span class="chapter-title">${esc(c.title)}</span><span class="status-dot ${c.audio_status==='completed'?'done':''}">${c.audio_status==='completed'?'Có audio':c.qa_count?`${c.qa_count} QA`:'Chưa tạo'}</span></div>`).join('');document.querySelectorAll('.chapter-row').forEach(el=>el.onclick=()=>openChapter(+el.dataset.id));$('#pageInfo').textContent=`${state.page*state.pageSize+1}–${Math.min((state.page+1)*state.pageSize,state.total)} / ${state.total}`;$('#prevPage').disabled=state.page===0;$('#nextPage').disabled=(state.page+1)*state.pageSize>=state.total}
async function openChapter(id){try{state.dialog=await api(`/api/chapters/${id}`);state.diffChapterId=null;state.diffRevisions=null;state.diffData=null;$('#dialogTitle').textContent=state.dialog.chapter.title;$('#qaIssues').innerHTML=state.dialog.qa_issues.slice(0,12).map(i=>`<div class="issue">${esc(i.message)}</div>`).join('');const box=$('#audioBox');if(state.dialog.audio_artifact){const url=`/api/artifacts/${state.dialog.audio_artifact.id}/file`;box.classList.remove('hidden');$('#chapterAudio').src=url;$('#audioFileLink').href=url}else{box.classList.add('hidden');$('#chapterAudio').removeAttribute('src')}showRevision('reflowed');$('#textDialog').showModal()}catch(e){toast(e.message,true)}}
function showRevision(kind){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===kind));if(kind==='casting'){openCasting();return}if(kind==='diff'){openTextDiff();return}$('#castingPanel').classList.add('hidden');$('#textDiffPanel').classList.add('hidden');$('#chapterText').classList.remove('hidden');const rev=state.dialog?.revisions.find(r=>r.kind===kind)||state.dialog?.revisions.find(r=>r.kind==='reflowed');$('#chapterText').textContent=rev?.text||'Chưa có revision này.'}
async function loadVoices(){const b=$('#loadVoices');b.disabled=true;b.textContent='Đang tải model…';try{const data=await api('/api/voices');state.voices=data.items;$('#voiceSelect').innerHTML=data.items.map(v=>`<option value="${esc(v.id)}">${esc(v.label)}</option>`).join('');toast(`Đã tải ${data.items.length} giọng`)}catch(e){toast(e.message,true)}finally{b.disabled=false;b.textContent='Tải giọng'}}
async function previewVoice(){const voiceId=$('#voiceSelect').value;if(!voiceId)return;const button=$('#previewVoice');button.disabled=true;button.textContent='Đang tạo preview…';try{const result=await api('/api/voice-previews',{method:'POST',body:JSON.stringify({voice_id:voiceId})});const audio=$('#voicePreviewAudio');audio.src=`${result.audio_url}?v=${result.cache_key}`;$('#voicePreviewBox').classList.remove('hidden');$('#voicePreviewStatus').textContent=`${(result.duration_ms/1000).toFixed(1)} giây · ${result.cache_hit?'dùng cache':'vừa tạo'}`;await audio.play().catch(()=>{});}catch(e){toast(e.message,true)}finally{button.disabled=!$('#voiceSelect').value;button.textContent='▶ Preview 10–20s'}}
async function preview(){if(!state.book)return;try{const f=+$('#fromChapter').value,t=+$('#toChapter').value;const p=await api(`/api/jobs/preview?book_id=${state.book.id}&from_chapter=${f}&to_chapter=${t}`);$('#preview').classList.remove('empty');$('#preview').innerHTML=`<strong>${p.total} chương</strong> · ${p.completed} đã có audio · ${p.pending} cần tạo<br><span class="muted">${p.characters.toLocaleString('vi-VN')} ký tự · khoảng ${p.estimated_audio_minutes} phút audio · ${p.estimated_processing_minutes} phút xử lý</span>`;state.previewOk=true;$('#runBtn').disabled=!$('#voiceSelect').value}catch(e){state.previewOk=false;$('#runBtn').disabled=true;toast(e.message,true)}}
async function runJob(){if(!state.previewOk||!state.book)return;const payload={book_id:state.book.id,from_chapter:+$('#fromChapter').value,to_chapter:+$('#toChapter').value,voice_name:$('#voiceSelect').value,repair_mode:$('#repairMode').value,output_format:$('#outputFormat').value,skip_completed:$('#skipCompleted').checked};try{const r=await api('/api/jobs',{method:'POST',body:JSON.stringify(payload)});toast(`Đã tạo job #${r.job_id}. Có ${state.config.undo_seconds} giây để hoàn tác.`);state.previewOk=false;$('#runBtn').disabled=true;await loadJobs()}catch(e){toast(e.message,true)}}
async function act(id,action){try{await api(`/api/jobs/${id}/${action}`,{method:'POST',body:'{}'});toast(`Đã gửi yêu cầu ${action}`);loadJobs()}catch(e){toast(e.message,true)}}window.act=act;
function castingVoiceOptions(selected=''){const voices=state.voices||[],known=voices.some(v=>v.id===selected);return (!known&&selected?`<option value="${esc(selected)}" selected disabled>[Missing] ${esc(selected)}</option>`:'')+voices.map(v=>`<option value="${esc(v.id)}" ${v.id===selected?'selected':''}>${esc(v.label)}</option>`).join('')}
const sourceLabels={character_override:'Character override',narrator:'Book narrator default',book_male:'Book male default',book_female:'Book female default',unknown_fallback:'Unknown fallback',legacy_snapshot:'Legacy snapshot'};
function resolutionText(r){if(!r)return 'No effective voice — create a Book Voice Profile.';return `Effective voice: ${r.resolved_voice_id} · Resolved from: ${sourceLabels[r.resolution_source]||r.resolution_source}${r.needs_review?' · Needs review':''}`}
function renderVoiceProfile(){const vp=state.casting.voice_profile||{},p=vp.profile,first=state.voices?.[0]?.id||'';$('#voiceProfileEmpty').classList.toggle('hidden',!!p);$('#voiceProfileMeta').textContent=p?`Profile v${p.config_version} · ${new Date(p.updated_at).toLocaleString('vi-VN')}`:'Not configured';$('#profileNarratorVoice').innerHTML=castingVoiceOptions(p?.narrator_voice_id||first);$('#profileMaleVoice').innerHTML=castingVoiceOptions(p?.male_dialogue_voice_id||first);$('#profileFemaleVoice').innerHTML=castingVoiceOptions(p?.female_dialogue_voice_id||first);$('#profileExplicitVoice').innerHTML=castingVoiceOptions(p?.unknown_voice_id||first);$('#profileUnknownFallback').value=p?.unknown_fallback||'narrator';profileFallbackChanged();const validation=vp.validation;$('#profileValidation').textContent=validation&&!validation.valid?`Missing preset: ${validation.missing_preset_ids.join(', ')}. Update the profile before creating a new casting plan.`:p?'Profile is valid.':'';$('#profileValidation').classList.toggle('error-text',!!validation&&!validation.valid);$('#saveVoiceProfile').textContent=p?'Save Voice Profile':'Create Voice Profile';document.querySelectorAll('[data-profile-preview]').forEach(b=>b.disabled=!profilePreviewVoiceId(b.dataset.profilePreview)||!!(validation&&!validation.valid))}
function profileFallbackChanged(){const explicit=$('#profileUnknownFallback').value==='explicit_voice';$('#profileExplicitVoiceLabel').classList.toggle('hidden',!explicit)}
function profilePreviewVoiceId(slot){if(slot==='narrator')return $('#profileNarratorVoice').value;if(slot==='male')return $('#profileMaleVoice').value;if(slot==='female')return $('#profileFemaleVoice').value;const policy=$('#profileUnknownFallback').value;return policy==='narrator'?$('#profileNarratorVoice').value:policy==='male_dialogue'?$('#profileMaleVoice').value:policy==='female_dialogue'?$('#profileFemaleVoice').value:$('#profileExplicitVoice').value}
async function previewProfileVoice(slot){const voiceId=profilePreviewVoiceId(slot);if(!voiceId)return;const button=document.querySelector(`[data-profile-preview="${slot}"]`);button.disabled=true;try{const result=await api('/api/voice-previews',{method:'POST',body:JSON.stringify({voice_id:voiceId})});const audio=$('#profilePreviewAudio');audio.src=`${result.audio_url}?v=${result.cache_key}`;$('#profilePreviewBox').classList.remove('hidden');$('#profilePreviewStatus').textContent=`${voiceId} · ${(result.duration_ms/1000).toFixed(1)} giây · ${result.cache_hit?'dùng cache':'vừa tạo'}`;await audio.play().catch(()=>{})}catch(e){toast(e.message,true)}finally{button.disabled=false}}
async function saveVoiceProfile(){const fallback=$('#profileUnknownFallback').value,payload={narrator_voice_id:$('#profileNarratorVoice').value,male_dialogue_voice_id:$('#profileMaleVoice').value,female_dialogue_voice_id:$('#profileFemaleVoice').value,unknown_fallback:fallback,unknown_voice_id:fallback==='explicit_voice'?$('#profileExplicitVoice').value:null};try{await api(`/api/books/${state.casting.chapter.book_id}/voice-profile`,{method:'PUT',body:JSON.stringify(payload)});toast('Đã lưu Book Voice Profile. Thay đổi chỉ áp dụng cho casting plan và job mới.');await openCasting()}catch(e){toast(e.message,true)}}
async function openCasting(){try{if(!state.voices?.length)await loadVoices();state.casting=await api(`/api/chapters/${state.dialog.chapter.id}/casting`);$('#chapterText').classList.add('hidden');$('#textDiffPanel').classList.add('hidden');$('#castingPanel').classList.remove('hidden');renderCasting()}catch(e){toast(e.message,true)}}
function utteranceResolution(u){if(u.resolution_source)return {resolved_voice_id:u.resolved_voice_id,resolution_source:u.resolution_source,gender:u.resolved_gender,needs_review:u.needs_review};if(u.role==='character'){return state.casting.characters.find(c=>c.id===u.character_id)?.effective_resolution||null}return state.casting.voice_profile?.narrator_resolution||null}
function renderCasting(){const context=state.casting,casting=context.casting,plan=casting.plan,vp=context.voice_profile||{},p=vp.profile;renderVoiceProfile();$('#castingNarratorVoice').innerHTML=castingVoiceOptions(p?.narrator_voice_id||casting.narrator_voice_id||$('#voiceSelect').value);$('#castingNarratorVoice').disabled=!!p;$('#castingNarratorSource').textContent=p?'Resolved from Book narrator default':'Legacy manual narrator voice';$('#newCharacterVoice').innerHTML=castingVoiceOptions($('#castingNarratorVoice').value);$('#newCharacterVoice').classList.add('hidden');$('#castingPlanStatus').textContent=casting.id?`Plan v${casting.plan_revision} · ${casting.status}`:'Chưa có plan';$('#characterList').innerHTML=context.characters.map(c=>{const custom=!!c.voice_override_id;return `<div class="character-row"><input id="character-name-${c.id}" value="${esc(c.display_name)}"><select id="character-gender-${c.id}" onchange="refreshCharacterEffective(${c.id})"><option value="unknown" ${(c.gender||'unknown')==='unknown'?'selected':''}>Unknown</option><option value="male" ${c.gender==='male'?'selected':''}>Male</option><option value="female" ${c.gender==='female'?'selected':''}>Female</option></select><select id="character-assignment-${c.id}" onchange="toggleCharacterVoice(${c.id})"><option value="default" ${custom?'':'selected'}>Use book default</option><option value="custom" ${custom?'selected':''}>Use custom voice</option></select><select id="character-voice-${c.id}" class="${custom?'':'hidden'}" onchange="refreshCharacterEffective(${c.id})">${castingVoiceOptions(c.voice_override_id||'')}</select><div id="character-effective-${c.id}" class="effective-voice ${c.effective_resolution?.needs_review?'needs-review':''}">${esc(resolutionText(c.effective_resolution))}</div><button onclick="saveCharacter(${c.id})">Lưu</button><button onclick="deleteCharacter(${c.id})">Xóa</button></div>`}).join('')||'<p class="muted">Chưa có nhân vật.</p>';const speakerOptions=u=>`<option value="narrator" ${u.role==='narrator'?'selected':''}>Narrator</option>`+context.characters.map(c=>`<option value="character:${c.id}" ${u.character_id===c.id?'selected':''}>${esc(c.display_name)}</option>`).join('');$('#utteranceList').innerHTML=plan.utterances.map(u=>{const r=utteranceResolution(u);return `<div class="utterance-row"><span class="utterance-seq">${u.sequence}</span><div><select data-utterance="${esc(u.utterance_id)}" onchange="refreshUtteranceResolution(this)">${speakerOptions(u)}</select><small class="utterance-resolution ${r?.needs_review?'needs-review':''}">${esc(resolutionText(r))}${r?.gender?` · Gender: ${esc(r.gender)}`:''}</small></div><p>${esc(u.text||'')}</p></div>`}).join('');$('#utteranceCount').textContent=`${plan.utterances.length} utterance`;$('#saveCastingDraft').disabled=!p||!!(vp.validation&&!vp.validation.valid);$('#approveCastingPlan').disabled=!casting.id||casting.status!=='draft';$('#renderCastingPlan').disabled=!casting.id||casting.status!=='approved'}
function toggleCharacterVoice(id){$(`#character-voice-${id}`).classList.toggle('hidden',$(`#character-assignment-${id}`).value!=='custom');refreshCharacterEffective(id)}
async function refreshCharacterEffective(id){const custom=$(`#character-assignment-${id}`).value==='custom',payload={speaker_type:'dialogue',character_id:id,gender:$(`#character-gender-${id}`).value,use_character_override:custom,voice_override_id:custom?$(`#character-voice-${id}`).value:null};const target=$(`#character-effective-${id}`);try{const r=await api(`/api/books/${state.casting.chapter.book_id}/voice-profile/resolve`,{method:'POST',body:JSON.stringify(payload)});target.textContent=resolutionText(r);target.classList.toggle('needs-review',!!r.needs_review)}catch(e){target.textContent=e.message;target.classList.add('needs-review')}}
function refreshUtteranceResolution(select){const [role,id]=select.value.split(':'),r=role==='character'?state.casting.characters.find(c=>c.id===+id)?.effective_resolution:state.casting.voice_profile?.narrator_resolution;const el=select.parentElement.querySelector('.utterance-resolution');el.textContent=`${resolutionText(r)}${r?.gender?` · Gender: ${r.gender}`:''}`;el.classList.toggle('needs-review',!!r?.needs_review)}
async function addCharacter(){const custom=$('#newCharacterAssignment').value==='custom';try{await api(`/api/books/${state.casting.chapter.book_id}/characters`,{method:'POST',body:JSON.stringify({display_name:$('#newCharacterName').value,gender:$('#newCharacterGender').value,voice_override_id:custom?$('#newCharacterVoice').value:null})});$('#newCharacterName').value='';await openCasting()}catch(e){toast(e.message,true)}}
async function saveCharacter(id){const custom=$(`#character-assignment-${id}`).value==='custom';try{await api(`/api/characters/${id}`,{method:'PATCH',body:JSON.stringify({display_name:$(`#character-name-${id}`).value})});await api(`/api/characters/${id}/voice-override`,{method:'PUT',body:JSON.stringify({gender:$(`#character-gender-${id}`).value,voice_override_id:custom?$(`#character-voice-${id}`).value:null})});toast(custom?'Đã lưu custom voice override.':'Đã chuyển sang book default.');await openCasting()}catch(e){toast(e.message,true)}}
async function deleteCharacter(id){try{await api(`/api/characters/${id}`,{method:'DELETE'});await openCasting()}catch(e){toast(e.message,true)}}
async function saveCastingDraft(){try{const assignments=[...document.querySelectorAll('[data-utterance]')].map(el=>{const [role,id]=el.value.split(':');return {utterance_id:el.dataset.utterance,role,character_id:role==='character'?+id:null}});await api(`/api/chapters/${state.dialog.chapter.id}/casting/draft`,{method:'POST',body:JSON.stringify({text_revision_id:state.casting.casting.text_revision_id,narrator_voice_id:$('#castingNarratorVoice').value,assignments})});toast('Đã lưu casting draft mới.');await openCasting()}catch(e){toast(e.message,true)}}
async function approveCastingPlan(){try{await api(`/api/casting/${state.casting.casting.id}/approve`,{method:'POST',body:'{}'});toast('Casting plan đã được approve và khóa bất biến.');await openCasting()}catch(e){toast(e.message,true)}}
async function renderCastingPlan(){const c=state.dialog.chapter,casting=state.casting.casting;try{const result=await api('/api/jobs',{method:'POST',body:JSON.stringify({book_id:c.book_id,from_chapter:c.chapter_number,to_chapter:c.chapter_number,voice_name:$('#castingNarratorVoice').value,repair_mode:'off',output_format:$('#outputFormat').value,skip_completed:false,casting_plan_id:casting.id})});toast(`Đã tạo multi-voice job #${result.job_id}`);$('#textDialog').close();await loadJobs()}catch(e){toast(e.message,true)}}
window.saveCharacter=saveCharacter;window.deleteCharacter=deleteCharacter;window.toggleCharacterVoice=toggleCharacterVoice;window.refreshCharacterEffective=refreshCharacterEffective;window.refreshUtteranceResolution=refreshUtteranceResolution;
function revisionLabel(r){return `${r.kind} · #${r.id} · ${r.char_count.toLocaleString('vi-VN')} ký tự · ${r.short_hash}`}
function latestRevision(kind){return [...(state.diffRevisions||[])].reverse().find(r=>r.kind===kind)}
function setDiffPreset(leftKind,rightKind){const left=latestRevision(leftKind),right=latestRevision(rightKind);if(!left||!right)return;$('#diffRevisionA').value=left.id;$('#diffRevisionB').value=right.id;loadTextDiff()}
async function openTextDiff(){try{$('#chapterText').classList.add('hidden');$('#castingPanel').classList.add('hidden');$('#textDiffPanel').classList.remove('hidden');if(state.diffChapterId===state.dialog.chapter.id&&state.diffRevisions){renderDiffSelectors();return}$('#diffContent').innerHTML='<p class="muted">Đang tải danh sách revision…</p>';const data=await api(`/api/chapters/${state.dialog.chapter.id}/revisions`);state.diffChapterId=state.dialog.chapter.id;state.diffRevisions=data.items;state.diffData=null;state.diffMode='inline';renderDiffSelectors();const preferred=latestRevision('reflowed')&&latestRevision('repaired')?['reflowed','repaired']:latestRevision('raw')&&latestRevision('reflowed')?['raw','reflowed']:null;if(preferred)setDiffPreset(...preferred);else $('#diffContent').innerHTML='<p class="muted">Chapter cần ít nhất hai revision để tạo diff.</p>'}catch(e){$('#diffContent').textContent=e.message;toast(e.message,true)}}
function renderDiffSelectors(){const options=(state.diffRevisions||[]).map(r=>`<option value="${r.id}">${esc(revisionLabel(r))}</option>`).join('');$('#diffRevisionA').innerHTML=options;$('#diffRevisionB').innerHTML=options;document.querySelectorAll('[data-diff-preset]').forEach(button=>{const [a,b]=button.dataset.diffPreset.split(',');const missing=[a,b].filter(kind=>!latestRevision(kind));button.disabled=missing.length>0;button.title=missing.length?`Thiếu revision: ${missing.join(', ')}`:''})}
async function loadTextDiff(){const a=+$('#diffRevisionA').value,b=+$('#diffRevisionB').value;if(!a||!b)return;$('#diffContent').innerHTML='<p class="muted">Đang tính diff…</p>';try{state.diffData=await api(`/api/chapters/${state.dialog.chapter.id}/diff?revision_a=${a}&revision_b=${b}`);renderTextDiff()}catch(e){state.diffData=null;$('#diffContent').innerHTML=`<div class="issue">${esc(e.message)}</div>`}}
function visibleDiffText(value,operation){if(operation.whitespace_only&&$('#diffShowWhitespace').checked)return esc(value.replace(/ /g,'·').replace(/\t/g,'→').replace(/\n/g,'↵\n'));return esc(value)}
function renderDiffOperation(operation,side){let value=side==='left'?operation.left:operation.right;if(!value)return '';if(operation.whitespace_only&&!$('#diffShowWhitespace').checked)return '';const isEqual=operation.status==='equal';if(isEqual&&!$('#diffShowUnchanged').checked&&value.length>220)value=`${value.slice(0,90)} … ${value.slice(-90)}`;let cls='diff-equal';if(side==='left'&&['delete','replace'].includes(operation.status))cls='diff-removed';if(side==='right'&&['insert','replace'].includes(operation.status))cls='diff-added';return `<span class="${cls}${operation.whitespace_only?' diff-whitespace':''}">${visibleDiffText(value,operation)}</span>`}
function renderInlineBlock(block){if(block.status==='equal'&&block.collapsed_by_default&&!$('#diffShowUnchanged').checked)return '<div class="diff-collapsed">… phần không đổi đã thu gọn …</div>';const body=block.operations.map(op=>{if(op.status==='equal')return renderDiffOperation(op,'right');return renderDiffOperation(op,'left')+renderDiffOperation(op,'right')}).join('');return `<div class="diff-block ${block.status}">${body}</div>`}
function renderSideBlock(block){if(block.status==='equal'&&block.collapsed_by_default&&!$('#diffShowUnchanged').checked)return '<div class="diff-collapsed">… phần không đổi đã thu gọn …</div>';const left=block.operations.map(op=>renderDiffOperation(op,'left')).join(''),right=block.operations.map(op=>renderDiffOperation(op,'right')).join('');return `<div class="diff-side-row ${block.status}"><div>${left}</div><div>${right}</div></div>`}
function renderTextDiff(){const d=state.diffData;if(!d)return;const s=d.summary,meta=r=>`<div><strong>${esc(r.kind)} #${r.id}</strong><span>${esc(r.created_at)} · parent ${r.parent_revision_id??'—'} · ${esc(r.processor_version)} · ${esc(r.short_hash)}</span><span>${esc(r.status)}${r.is_active?' · active':''}${r.is_raw_selected?' · raw selected':''}</span></div>`;$('#diffRevisionMeta').innerHTML=meta(d.revision_a)+meta(d.revision_b);$('#diffSummary').innerHTML=`<div><strong>${s.blocks_changed}</strong><span>block thay đổi</span></div><div><strong>+${s.tokens_added} / −${s.tokens_removed}</strong><span>lexical token</span></div><div><strong>${s.punctuation_changes}</strong><span>punctuation</span></div><div><strong>${(s.change_ratio*100).toFixed(2)}%</strong><span>tỷ lệ lexical change</span></div><div><strong>${s.characters_a.toLocaleString('vi-VN')}</strong><span>ký tự A</span></div><div><strong>${s.characters_b.toLocaleString('vi-VN')}</strong><span>ký tự B</span></div>`;$('#diffWarnings').innerHTML=[...d.warnings,...(!s.lexical_integrity&&s.lexical_reason?[s.lexical_reason]:[])].map(w=>`<div class="issue">${esc(w)}</div>`).join('');$('#diffInlineMode').classList.toggle('active',state.diffMode!=='side');$('#diffSideMode').classList.toggle('active',state.diffMode==='side');$('#diffContent').className=`diff-content ${state.diffMode==='side'?'side':''}`;$('#diffContent').innerHTML=d.blocks.map(block=>state.diffMode==='side'?renderSideBlock(block):renderInlineBlock(block)).join('')||'<p class="muted">Hai revision trống.</p>'}
function bytes(n){if(n===null||n===undefined)return '—';if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`}
function statusBadge(status){return `<span class="badge ${esc(status)}">${esc(fmtStatus(status))}</span>`}
function fileState(item){if(!item.file_exists)return '<span class="diag-bad">Thiếu file</span>';if(item.hash_matches===false)return '<span class="diag-bad">Sai hash</span>';return '<span class="diag-good">Hợp lệ</span>'}

async function loadJobs(){try{const jobs=await api('/api/jobs');$('#jobs').innerHTML=jobs.map(j=>{const done=j.actual_completed||0,total=j.total_chapters||0,pct=total?Math.round(done*100/total):100;return `<div class="job-card"><div class="job-top"><div><div class="job-title">#${j.id} · ${esc(j.book_title)} · Chương ${j.from_chapter}–${j.to_chapter}</div><div class="job-meta">${esc(j.voice_name)} · ${esc(j.repair_mode)} · ${esc(j.output_format.toUpperCase())}${j.current_chapter_number?` · hiện tại chương ${j.current_chapter_number}`:''}</div></div>${statusBadge(j.status)}</div><div class="progress"><span style="width:${pct}%"></span></div><div class="job-meta">${done}/${total} chương · ${j.completed_segments||0}/${j.total_segments||0} segment${j.actual_failed?` · ${j.actual_failed} lỗi`:''}</div>${j.error_message?`<div class="issue">${esc(j.error_message)}</div>`:''}<div class="job-actions"><button onclick="openJobDiagnostics(${j.id})">Chẩn đoán</button>${['scheduled','queued','running','repairing','synthesizing','assembling'].includes(j.status)?`<button onclick="act(${j.id},'pause')">Tạm dừng</button><button onclick="act(${j.id},'cancel')">Hủy</button>`:''}${j.status==='paused'?`<button onclick="act(${j.id},'resume')">Tiếp tục</button><button onclick="act(${j.id},'cancel')">Hủy</button>`:''}${['completed_with_errors','failed'].includes(j.status)?`<button onclick="act(${j.id},'retry')">Thử lại phần lỗi</button>`:''}</div></div>`}).join('')||'<p class="muted">Chưa có job.</p>'}catch(e){console.error(e)}}

async function openJobDiagnostics(id){try{const data=await api(`/api/diagnostics/jobs/${id}`);state.diagnosticJobId=id;$('#jobDiagnosticTitle').textContent=`Job #${id} · ${data.job.book_title}`;const counts=Object.entries(data.summary.chapter_status_counts).map(([s,n])=>`<span>${statusBadge(s)} ${n}</span>`).join('');$('#jobDiagnosticBody').innerHTML=`<div class="diag-summary"><div><strong>${data.summary.chapter_total}</strong><span>chương</span></div><div><strong>${data.summary.segment_verified}/${data.summary.segment_total}</strong><span>segment hợp lệ</span></div><div><strong>${data.summary.segment_failed}</strong><span>segment lỗi</span></div><div><strong>${data.summary.repair_failed}</strong><span>Gemini lỗi</span></div></div><div class="diag-line">${statusBadge(data.job.status)} <span>${counts}</span></div>${data.job.error_message?`<div class="issue">${esc(data.job.error_message)}</div>`:''}<h3>Chương</h3><div class="diag-table-wrap"><table class="diag-table"><thead><tr><th>Chương</th><th>Trạng thái</th><th>Gemini</th><th>Segment</th><th>Audio</th><th></th></tr></thead><tbody>${data.chapters.map(c=>`<tr><td>${c.chapter_number}. ${esc(c.title)}</td><td>${statusBadge(c.status)}${c.error_message?`<small>${esc(c.error_message)}</small>`:''}</td><td>${c.repair_failed}/${c.repair_total} lỗi</td><td>${c.segment_verified}/${c.segment_total}${c.segment_failed?` · ${c.segment_failed} lỗi`:''}</td><td>${c.artifact_active?'Có':'—'}</td><td class="diag-actions"><button onclick="openChapterDiagnostics(${c.job_chapter_id})">Chi tiết</button>${['failed','needs_review','cancelled','interrupted'].includes(c.status)?`<button onclick="retryChapter(${c.job_chapter_id})">Thử lại</button>`:''}</td></tr>`).join('')}</tbody></table></div><details><summary>Cấu hình snapshot</summary><pre class="diag-json">${esc(JSON.stringify(data.job.settings,null,2))}</pre></details><details><summary>Nhật ký gần đây (${data.events.length})</summary><div class="event-list">${data.events.map(e=>`<div><code>${esc(e.event_code)}</code><span>${esc(e.created_at)}</span></div>`).join('')||'Chưa có sự kiện.'}</div></details>`;$('#chapterDiagnosticsDialog').close();$('#segmentDiagnosticsDialog').close();if(!$('#jobDiagnosticsDialog').open)$('#jobDiagnosticsDialog').showModal()}catch(e){toast(e.message,true)}}

async function openChapterDiagnostics(id){try{const data=await api(`/api/diagnostics/job-chapters/${id}`);state.diagnosticChapterId=id;state.diagnosticJobId=data.chapter.job_id;$('#chapterDiagnosticTitle').textContent=`Chương ${data.chapter.chapter_number} · ${data.chapter.title}`;const rev=data.text_revision;$('#chapterDiagnosticBody').innerHTML=`<div class="diag-line">${statusBadge(data.chapter.status)}${rev?`<span>Revision #${rev.id} · ${esc(rev.kind)} · ${rev.char_count.toLocaleString('vi-VN')} ký tự</span>`:'<span>Chưa gắn text revision</span>'}</div>${data.chapter.error_message?`<div class="issue">${esc(data.chapter.error_message)}</div>`:''}<h3>Gemini repair blocks (${data.repair_blocks.length})</h3>${data.repair_blocks.length?`<div class="diag-table-wrap"><table class="diag-table"><thead><tr><th>#</th><th>Trạng thái</th><th>Lần thử</th><th>Source</th><th>Output</th><th>Lỗi</th></tr></thead><tbody>${data.repair_blocks.map(b=>`<tr><td>${b.block_index}</td><td>${statusBadge(b.status)}</td><td>${b.attempt_count}</td><td>${b.source_file_exists?'Có':'Thiếu'}</td><td>${b.repaired_file_exists?'Có':'—'}</td><td>${esc(b.error_message||'')}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Không dùng Gemini repair cho chương này.</p>'}<h3>Segments (${data.segments.length})</h3><div class="diag-table-wrap"><table class="diag-table"><thead><tr><th>#</th><th>Trạng thái</th><th>Text</th><th>Audio</th><th>Thời lượng</th><th></th></tr></thead><tbody>${data.segments.map(s=>`<tr><td>${s.segment_index}</td><td>${statusBadge(s.status)}${s.error_message?`<small>${esc(s.error_message)}</small>`:''}</td><td class="diag-preview">${esc(s.text_preview||'—')}</td><td>${fileState(s)} · ${bytes(s.actual_size_bytes)}</td><td>${s.duration_ms?`${(s.duration_ms/1000).toFixed(1)}s`:'—'}</td><td class="diag-actions"><button onclick="openSegmentDiagnostics(${s.id})">Chi tiết</button>${['failed','interrupted'].includes(s.status)?`<button onclick="retrySegmentAction(${s.id})">Thử lại</button>`:''}</td></tr>`).join('')}</tbody></table></div><h3>Artifacts (${data.artifacts.length})</h3>${data.artifacts.length?`<div class="diag-table-wrap"><table class="diag-table"><thead><tr><th>Loại</th><th>Trạng thái</th><th>File</th><th>Kích thước</th></tr></thead><tbody>${data.artifacts.map(a=>`<tr><td>${esc(a.artifact_type)}</td><td>${statusBadge(a.status)}</td><td>${fileState(a)} · ${esc(a.filename||'—')}</td><td>${bytes(a.actual_size_bytes)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Chưa có artifact.</p>'}`;$('#jobDiagnosticsDialog').close();$('#segmentDiagnosticsDialog').close();if(!$('#chapterDiagnosticsDialog').open)$('#chapterDiagnosticsDialog').showModal()}catch(e){toast(e.message,true)}}

async function openSegmentDiagnostics(id){try{const s=await api(`/api/diagnostics/segments/${id}`);state.diagnosticSegmentId=id;state.diagnosticChapterId=s.job_chapter_id;$('#segmentDiagnosticTitle').textContent=`Segment #${s.segment_index} · Chương ${s.chapter_number}`;$('#segmentDiagnosticBody').innerHTML=`<div class="diag-line">${statusBadge(s.status)}<span>Lần thử: ${s.attempt_count}</span><span>Thời lượng: ${s.duration_ms?`${(s.duration_ms/1000).toFixed(2)}s`:'—'}</span></div>${s.error_message?`<div class="issue">${esc(s.error_message)}</div>`:''}<h3>Text đầu vào</h3><pre class="segment-text">${esc(s.text_preview||'Không đọc được text blob.')}</pre><div class="file-grid"><div><strong>Text blob</strong>${fileState(s.text_file)}<span>${bytes(s.text_file.actual_size_bytes)}</span></div><div><strong>WAV segment</strong>${fileState(s.audio_file)}<span>${bytes(s.audio_file.actual_size_bytes)}</span></div></div>${['failed','interrupted'].includes(s.status)?`<button class="primary" onclick="retrySegmentAction(${s.id})">Thử lại segment này</button>`:''}`;$('#chapterDiagnosticsDialog').close();if(!$('#segmentDiagnosticsDialog').open)$('#segmentDiagnosticsDialog').showModal()}catch(e){toast(e.message,true)}}

async function retryChapter(id){try{const r=await api(`/api/job-chapters/${id}/retry`,{method:'POST',body:'{}'});toast(`Đã xếp lại chương; giữ nguyên ${r.verified_segments_reused} segment hợp lệ.`);$('#chapterDiagnosticsDialog').close();await loadJobs();await openJobDiagnostics(state.diagnosticJobId)}catch(e){toast(e.message,true)}}
async function retrySegmentAction(id){try{await api(`/api/segments/${id}/retry`,{method:'POST',body:'{}'});toast('Đã xếp lại segment lỗi; các segment hợp lệ được giữ nguyên.');$('#segmentDiagnosticsDialog').close();await loadJobs();await openJobDiagnostics(state.diagnosticJobId)}catch(e){toast(e.message,true)}}

window.openJobDiagnostics=openJobDiagnostics;window.openChapterDiagnostics=openChapterDiagnostics;window.openSegmentDiagnostics=openSegmentDiagnostics;window.retryChapter=retryChapter;window.retrySegmentAction=retrySegmentAction;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#importBtn').onclick=async()=>{try{const r=await api('/api/books/import',{method:'POST',body:JSON.stringify({path:$('#epubPath').value})});toast(r.created?`Đã nhập ${r.chapter_count} chương`:'Sách đã tồn tại');await loadBooks();selectBook(r.book_id)}catch(e){toast(e.message,true)}};
$('#loadVoices').onclick=async()=>{await loadVoices();$('#previewVoice').disabled=!$('#voiceSelect').value};$('#previewVoice').onclick=previewVoice;$('#previewBtn').onclick=preview;$('#runBtn').onclick=runJob;$('#refreshJobs').onclick=loadJobs;$('#searchBtn').onclick=()=>{state.page=0;loadChapters()};$('#prevPage').onclick=()=>{state.page--;loadChapters()};$('#nextPage').onclick=()=>{state.page++;loadChapters()};$('#closeDialog').onclick=()=>$('#textDialog').close();document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>showRevision(b.dataset.tab));['fromChapter','toChapter','voiceSelect','repairMode','outputFormat','skipCompleted'].forEach(id=>$('#'+id).addEventListener('change',()=>{state.previewOk=false;$('#runBtn').disabled=true}));$('#voiceSelect').addEventListener('change',()=>{const audio=$('#voicePreviewAudio');audio.pause();audio.removeAttribute('src');$('#voicePreviewBox').classList.add('hidden');$('#previewVoice').disabled=!$('#voiceSelect').value});init();
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>$('#'+button.dataset.close).close());
$('#backToJobDiagnostic').onclick=()=>{ $('#chapterDiagnosticsDialog').close(); openJobDiagnostics(state.diagnosticJobId) };
$('#backToChapterDiagnostic').onclick=()=>{ $('#segmentDiagnosticsDialog').close(); openChapterDiagnostics(state.diagnosticChapterId) };
$('#addCharacterBtn').onclick=addCharacter;
$('#saveVoiceProfile').onclick=saveVoiceProfile;
$('#profileUnknownFallback').onchange=()=>{profileFallbackChanged();document.querySelectorAll('[data-profile-preview]').forEach(b=>b.disabled=!profilePreviewVoiceId(b.dataset.profilePreview))};
document.querySelectorAll('[data-profile-preview]').forEach(button=>button.onclick=()=>previewProfileVoice(button.dataset.profilePreview));
$('#newCharacterAssignment').onchange=()=>$('#newCharacterVoice').classList.toggle('hidden',$('#newCharacterAssignment').value!=='custom');
$('#saveCastingDraft').onclick=saveCastingDraft;
$('#approveCastingPlan').onclick=approveCastingPlan;
$('#renderCastingPlan').onclick=renderCastingPlan;
$('#loadTextDiff').onclick=loadTextDiff;
document.querySelectorAll('[data-diff-preset]').forEach(button=>button.onclick=()=>setDiffPreset(...button.dataset.diffPreset.split(',')));
$('#diffInlineMode').onclick=()=>{state.diffMode='inline';renderTextDiff()};
$('#diffSideMode').onclick=()=>{state.diffMode='side';renderTextDiff()};
$('#diffShowWhitespace').onchange=renderTextDiff;
$('#diffShowUnchanged').onchange=renderTextDiff;
