const $=s=>document.querySelector(s);let state={config:null,books:[],book:null,page:0,pageSize:100,total:0,previewOk:false,dialog:null};
async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let data;try{data=await r.json()}catch{data={detail:await r.text()}}if(!r.ok)throw new Error(data.detail||data.error||'Yêu cầu thất bại');return data}
function toast(msg,error=false){const el=$('#toast');el.textContent=msg;el.className='toast'+(error?' error':'');setTimeout(()=>el.classList.add('hidden'),4500)}
function fmtStatus(s){return({scheduled:'Chờ hoàn tác',queued:'Đang chờ',running:'Đang chạy',repairing:'Gemini',synthesizing:'Đang đọc',assembling:'Đang ghép',paused:'Tạm dừng',completed:'Hoàn tất',completed_with_errors:'Xong có lỗi',failed:'Thất bại',cancelled:'Đã hủy',interrupted:'Bị gián đoạn'})[s]||s}
async function init(){try{state.config=await api('/api/config');$('#health').textContent=`Gemini: ${state.config.gemini_configured?'sẵn sàng':'chưa có key'} · VieNeu: ${state.config.tts_status}`;$('#epubPath').innerHTML=state.config.available_epubs.map(p=>`<option value="${p}">${p.split(/[\\/]/).pop()}</option>`).join('')||'<option>Không tìm thấy EPUB</option>';await loadBooks();await loadJobs()}catch(e){toast(e.message,true)}setInterval(loadJobs,2500)}
async function loadBooks(){state.books=await api('/api/books');$('#books').innerHTML=state.books.map(b=>`<div class="book-card ${state.book?.id===b.id?'active':''}" data-id="${b.id}"><strong>${esc(b.title)}</strong><span>${esc(b.author||'Không rõ tác giả')} · ${b.chapter_count} chương · ${b.audio_chapters||0} có audio</span></div>`).join('')||'<p class="muted">Chưa nhập sách.</p>';document.querySelectorAll('.book-card').forEach(el=>el.onclick=()=>selectBook(+el.dataset.id))}
async function selectBook(id){state.book=state.books.find(b=>b.id===id);state.page=0;state.previewOk=false;$('#workspace').classList.remove('hidden');$('#bookTitle').textContent=state.book.title;$('#chapterCount').textContent=`${state.book.chapter_count} chương`;$('#fromChapter').value=1;$('#toChapter').value=Math.min(10,state.book.chapter_count);await loadBooks();await loadChapters()}
async function loadChapters(){if(!state.book)return;const q=encodeURIComponent($('#chapterQuery').value.trim());const data=await api(`/api/books/${state.book.id}/chapters?offset=${state.page*state.pageSize}&limit=${state.pageSize}&query=${q}`);state.total=data.total;$('#chapterList').innerHTML=data.items.map(c=>`<div class="chapter-row" data-id="${c.id}"><span class="chapter-number">${c.chapter_number}</span><span class="chapter-title">${esc(c.title)}</span><span class="status-dot ${c.audio_status==='completed'?'done':''}">${c.audio_status==='completed'?'Có audio':c.qa_count?`${c.qa_count} QA`:'Chưa tạo'}</span></div>`).join('');document.querySelectorAll('.chapter-row').forEach(el=>el.onclick=()=>openChapter(+el.dataset.id));$('#pageInfo').textContent=`${state.page*state.pageSize+1}–${Math.min((state.page+1)*state.pageSize,state.total)} / ${state.total}`;$('#prevPage').disabled=state.page===0;$('#nextPage').disabled=(state.page+1)*state.pageSize>=state.total}
async function openChapter(id){try{state.dialog=await api(`/api/chapters/${id}`);$('#dialogTitle').textContent=state.dialog.chapter.title;$('#qaIssues').innerHTML=state.dialog.qa_issues.slice(0,12).map(i=>`<div class="issue">${esc(i.message)}</div>`).join('');const box=$('#audioBox');if(state.dialog.audio_artifact){const url=`/api/artifacts/${state.dialog.audio_artifact.id}/file`;box.classList.remove('hidden');$('#chapterAudio').src=url;$('#audioFileLink').href=url}else{box.classList.add('hidden');$('#chapterAudio').removeAttribute('src')}showRevision('reflowed');$('#textDialog').showModal()}catch(e){toast(e.message,true)}}
function showRevision(kind){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===kind));const rev=state.dialog?.revisions.find(r=>r.kind===kind)||state.dialog?.revisions.find(r=>r.kind==='reflowed');$('#chapterText').textContent=rev?.text||'Chưa có revision này.'}
async function loadVoices(){const b=$('#loadVoices');b.disabled=true;b.textContent='Đang tải model…';try{const data=await api('/api/voices');$('#voiceSelect').innerHTML=data.items.map(v=>`<option value="${esc(v.id)}">${esc(v.label)}</option>`).join('');toast(`Đã tải ${data.items.length} giọng`)}catch(e){toast(e.message,true)}finally{b.disabled=false;b.textContent='Tải giọng'}}
async function preview(){if(!state.book)return;try{const f=+$('#fromChapter').value,t=+$('#toChapter').value;const p=await api(`/api/jobs/preview?book_id=${state.book.id}&from_chapter=${f}&to_chapter=${t}`);$('#preview').classList.remove('empty');$('#preview').innerHTML=`<strong>${p.total} chương</strong> · ${p.completed} đã có audio · ${p.pending} cần tạo<br><span class="muted">${p.characters.toLocaleString('vi-VN')} ký tự · khoảng ${p.estimated_audio_minutes} phút audio · ${p.estimated_processing_minutes} phút xử lý</span>`;state.previewOk=true;$('#runBtn').disabled=!$('#voiceSelect').value}catch(e){state.previewOk=false;$('#runBtn').disabled=true;toast(e.message,true)}}
async function runJob(){if(!state.previewOk||!state.book)return;const payload={book_id:state.book.id,from_chapter:+$('#fromChapter').value,to_chapter:+$('#toChapter').value,voice_name:$('#voiceSelect').value,repair_mode:$('#repairMode').value,output_format:$('#outputFormat').value,skip_completed:$('#skipCompleted').checked};try{const r=await api('/api/jobs',{method:'POST',body:JSON.stringify(payload)});toast(`Đã tạo job #${r.job_id}. Có ${state.config.undo_seconds} giây để hoàn tác.`);state.previewOk=false;$('#runBtn').disabled=true;await loadJobs()}catch(e){toast(e.message,true)}}
async function loadJobs(){try{const jobs=await api('/api/jobs');$('#jobs').innerHTML=jobs.map(j=>{const done=j.actual_completed||0,total=j.total_chapters||0,pct=total?Math.round(done*100/total):100;const playable=j.status==='completed'&&done>0;return `<div class="job-card"><div class="job-top"><div><div class="job-title">#${j.id} · ${esc(j.book_title)} · Chương ${j.from_chapter}–${j.to_chapter}</div><div class="job-meta">${esc(j.voice_name)} · ${j.repair_mode} · ${j.output_format.toUpperCase()}${j.current_chapter_number?` · hiện tại chương ${j.current_chapter_number}`:''}</div></div><span class="badge ${j.status}">${fmtStatus(j.status)}</span></div><div class="progress"><span style="width:${pct}%"></span></div><div class="job-meta">${done}/${total} chương · ${j.completed_segments||0}/${j.total_segments||0} segment${j.actual_failed?` · ${j.actual_failed} lỗi`:''}</div>${j.error_message?`<div class="issue">${esc(j.error_message)}</div>`:''}<div class="job-actions">${['scheduled','queued','running','repairing','synthesizing','assembling'].includes(j.status)?`<button onclick="act(${j.id},'pause')">Tạm dừng</button><button onclick="act(${j.id},'cancel')">Hủy</button>`:''}${j.status==='paused'?`<button onclick="act(${j.id},'resume')">Tiếp tục</button><button onclick="act(${j.id},'cancel')">Hủy</button>`:''}${['completed_with_errors','failed'].includes(j.status)?`<button onclick="act(${j.id},'retry')">Thử lại phần lỗi</button>`:''}</div></div>`}).join('')||'<p class="muted">Chưa có job.</p>'}catch(e){console.error(e)}}
async function act(id,action){try{await api(`/api/jobs/${id}/${action}`,{method:'POST',body:'{}'});toast(`Đã gửi yêu cầu ${action}`);loadJobs()}catch(e){toast(e.message,true)}}window.act=act;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#importBtn').onclick=async()=>{try{const r=await api('/api/books/import',{method:'POST',body:JSON.stringify({path:$('#epubPath').value})});toast(r.created?`Đã nhập ${r.chapter_count} chương`:'Sách đã tồn tại');await loadBooks();selectBook(r.book_id)}catch(e){toast(e.message,true)}};
$('#loadVoices').onclick=loadVoices;$('#previewBtn').onclick=preview;$('#runBtn').onclick=runJob;$('#refreshJobs').onclick=loadJobs;$('#searchBtn').onclick=()=>{state.page=0;loadChapters()};$('#prevPage').onclick=()=>{state.page--;loadChapters()};$('#nextPage').onclick=()=>{state.page++;loadChapters()};$('#closeDialog').onclick=()=>$('#textDialog').close();document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>showRevision(b.dataset.tab));['fromChapter','toChapter','voiceSelect','repairMode','outputFormat','skipCompleted'].forEach(id=>$('#'+id).addEventListener('change',()=>{state.previewOk=false;$('#runBtn').disabled=true}));init();
